# Generated by Django 5.0.1 on 2024-02-25 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('subject', models.TextField(blank=True)),
                ('message', models.TextField(blank=True)),
                ('type', models.IntegerField(choices=[(1, 'Error'), (2, 'Warning'), (3, 'Tip')])),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
