# Generated by Django 5.0.1 on 2024-03-08 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoomAccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('access_token', models.TextField()),
            ],
            options={
                'ordering': ['-created'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='meetingproposal',
            name='meeting_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meetingproposal',
            name='meeting_location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meetingproposal',
            name='meeting_type',
            field=models.IntegerField(choices=[(1, 'Online'), (2, 'In Person')], default=2),
        ),
    ]
