# Generated by Django 5.0.1 on 2024-02-02 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_country'),
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='conversations',
            field=models.ManyToManyField(blank=True, to='messaging.conversation'),
        ),
        migrations.AddField(
            model_name='user',
            name='experience_level',
            field=models.IntegerField(choices=[(1, 'Entry Level'), (2, 'Intermediate'), (3, 'Mid Level'), (4, 'Senior')], default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='learning_interests',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='skills',
            field=models.ManyToManyField(blank=True, to='accounts.skill'),
        ),
    ]
