# Generated by Django 5.0.1 on 2024-02-05 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_skill_user_conversations_user_experience_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='skills',
            field=models.ManyToManyField(blank=True, default=list, to='accounts.skill'),
        ),
    ]
