# Generated by Django 5.0.1 on 2024-02-07 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0002_trainedmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='user1',
        ),
        migrations.RemoveField(
            model_name='match',
            name='user2',
        ),
        migrations.DeleteModel(
            name='TrainedModel',
        ),
        migrations.DeleteModel(
            name='Match',
        ),
    ]
